name: Build and Push Backend Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allows manual trigger

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 539247487622.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPOSITORY: todo-backend
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image (AMD64)
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Image Details
      run: |
        echo "Image pushed to: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
        echo "Git SHA tag: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
